[package]
name = "mariochao/data-store-reader"
description = "Module class for reading all of datastore."

version = "0.0.3"
license = ""
authors = ["Mario Chao"]
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"
repository = ""

[dependencies]
